name: Continuous Integration

on: [ push ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@2.3.0
        with:
          cmd: build
      - uses: borales/actions-yarn@2.3.0
        with:
          cmd: test