name: Continuous Integration

on: [ push ]

jobs:
  build:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Super-Linter
        uses: github/super-linter@v4
      
      - name: GitHub Action for Yarn
        uses: borales/actions-yarn@2.3.0
        with:
          cmd: install
      
      - name: GitHub Action for Yarn
        uses: borales/actions-yarn@2.3.0
        with:
          cmd: build
      - name: GitHub Action for Yarn
        uses: borales/actions-yarn@2.3.0
        with:
          cmd: test
