name: Run tests on Codebase

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2

      - name: Setup Node
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: yarn
      - run: yarn test
  
